### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by AppWerft** [trevorf/ti-android-streamer#1]
Hi Trevor,

long time I was waiting for this functionality. Now I tried to compile. After fitting to my machine (paths) I get:

```
There is discrepancy between the architectures specified in manifest and compiled binary.
```

Here is you manifest:

```
# these should not be edited
name: androidaudiostreamer
moduleid: com.woohoo.androidaudiostreamer
guid: 1f81e1bf-afd5-4075-a219-d2c51accde23
platform: android
```

Update:
I have inserted 

```
architectures: armeabi armeabi-v7a x86
```

and now it works.

PS a better module name would be: shoutcaststreamer

**Comment by trevorf** [comment]
Hi AppWerft,

Was just going to reply regarding this fix and have just merged a commit from <a href="https://github.com/manumaticx">manumaticx</a> that introduces this fix.

I haven't made reference to shoutcast in the name as you should be able to stream from other servers and even locally stored files too.

Trevor

**Comment by AppWerft** [comment]
Thanks Trevor. I will try it ion my radio app (purpose: displaying of live text during transmission). With locale file: it is without meta?

**Comment by trevorf** [comment]
I've not tested retrieving metadata when streaming a local file, only remote live streams which works fine if it's provided.

**Comment by AppWerft** [comment]
I think metadata are only available  by live streaming. 
Unfortunately I see a little issue: If I  embed your awesome module in tiapp.xml (without using in code), then the app crashes and on console comes:

[ERROR] :  art: dlopen("/data/app/de.appwerft.dlrmediathek-2/lib/arm/libcom.woohoo.androidaudiostreamer.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.woohoo.androidaudiostreamer.so"...
[INFO] :   Process: Sending signal. PID: 1718 SIG: 9

I have opened a new issue.

**Comment by PatrickMounteney** [comment]
Sorry, I am getting the these errors in the Ti Studio Console when trying to install the module:
[ERROR] com.woohoo.androidaudiostreamer:commonjs no distributable available
[ERROR] com.woohoo.androidaudiostreamer:android no distributable available

using: gittio install com.woohoo.androidaudiostreamer
What are I doing wrong I wonder?

**Comment by AppWerft** [comment]
1. there is no commonjs variant ;-)
2. there is no ready to go version on github. You have to compile the module by yourself (or ask me for pm)

**Comment by PatrickMounteney** [comment]
> On 6 Jan 2016, at 10:08, Rainer Schleevoigt notifications@github.com wrote:
> 
> there is no commonjs variant ;-)
> there is no ready to go version on github. You have to compile the module by yourself (or ask me for pm)

Hello Trevor,

I did buy the 1.7.1 version and hoped this was an update to it. Where is a compile guide? And do I have to have ‘Ant’ install in Studio to compile the module?

I dunno - questions, questions...

Best,

Patrick

**Comment by AppWerft** [comment]
For compiling you need sources. In this case you go into, edit the 
build.properties and start 'ant'. It is simple.

Am 06/01/16 um 11:14 schrieb PatrickMounteney:

> > On 6 Jan 2016, at 10:08, Rainer Schleevoigt 
> > notifications@github.com wrote:
> > 
> > there is no commonjs variant ;-)
> > there is no ready to go version on github. You have to compile the 
> > module by yourself (or ask me for pm)
> 
> Hello Trevor,
> 
> I did buy the 1.7.1 version and hoped this was an update to it. Where 
> is a compile guide? And do I have to have ‘Ant’ install in Studio to 
> compile the module?
> 
> I dunno - questions, questions...
> 
> Best,
> 
> Patrick
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/trevorf/ti-android-streamer/issues/1#issuecomment-169284054.

## 

_Dipl.-Ing. Rainer Schleevoigt_
Certified TYPO3 Integrator
Certified Titanium App Developer

```
Novalisweg 10
```

22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||

**Comment by PatrickMounteney** [comment]
Ah ha - it's easy if you have done it a few times, but not if you've never done this for Android (I have for iOS).
I have installed Android NDK and set it's 'Home' path, installed Ant and made a bash_profile with paths:
export ANT_HOME="/Users/patrick/apache-ant-1.9.6"
export PATH=$PATH:$ANT_HOME/bin

In Console I have change the directory to the 'ti-android-streamer-master' folder and typed both 'ant build' and 'ant build.xml' - both fail with  a '...does not exist in the project "androidaudiostreamer"' error.

Next I tried to import the ti-android-streamer-master into Appcelerator Studio, right clicked on build.xml and use 'Run As... > Ant Build' as in Appcelerator's 'Android Module Project' documentation. But it simply opens 'Run Configurations' where there is no 'Ant Build' command. 

So I am now stuck! Interesting though.....

**Comment by AppWerft** [comment]
Hi,

here is my build.properties file:

titanium.platform=/Users/fuerst/Library/Application 
Support/Titanium/mobilesdk/osx/4.1.0.GA/android
android.platform=/Users/fuerst/Library/android-sdk/platforms/android-10
android.ndk=/Users/fuerst/Library/android-ndk
google.apis=/Users/fuerst/android-sdk/add-ons/addon-google_apis-google-10

its all, Now you can start 'ant' on console.

Am 06/01/16 um 16:59 schrieb PatrickMounteney:

> Ah ha - it's easy if you have done it a few times, but not if you've 
> never done this for Android (I have for iOS).
> I have installed Android NDK and set it's 'Home' path, installed Ant 
> and made a bash_profile with paths:
> export ANT_HOME="/Users/patrick/apache-ant-1.9.6"
> export PATH=$PATH:$ANT_HOME/bin
> 
> In Console I have change the directory to the 
> 'ti-android-streamer-master' folder and typed both 'ant build' and 
> 'ant build.xml' - both fail with a '...does not exist in the project 
> "androidaudiostreamer"' error.
> 
> Next I tried to import the ti-android-streamer-master into 
> Appcelerator Studio, right clicked on build.xml and use 'Run As... > 
> Ant Build' as in Appcelerator's 'Android Module Project' 
> documentation. But it simply opens 'Run Configurations' where there is 
> no 'Ant Build' command.
> 
> So I am now stuck! Interesting though.....
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/trevorf/ti-android-streamer/issues/1#issuecomment-169367925.

## 

_Dipl.-Ing. Rainer Schleevoigt_
Certified TYPO3 Integrator
Certified Titanium App Developer

```
Novalisweg 10
```

22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||
