### ISSUE TITLE
Problem with using

### ISSUE THREAD

**Issue by AppWerft** [trevorf/ti-android-streamer#3]
Hi Trevor,

now I have successful compiled and only embed:

```
var Shoutcast = require('com.woohoo.androidaudiostreamer');
```

After this appears:

```
[ERROR] :  art: dlopen("/data/app/de.appwerft.dlrmediathek-1/lib/arm/libcom.woohoo.androidaudiostreamer.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.woohoo.androidaudiostreamer.so"...
```

SDK 3.5.1 (Patch manumatixc) and SDK 4.1.0.GA
 Testing on NEXUS5 and Caterpillar S40

UPDATE:
it happens if I only embed in tiapp.xml, without calling in code ;-(

Here a hint in QA: https://community.appcelerator.com/topic/384/android-module-issue-on-4-0/4

**Comment by trevorf** [comment]
This may be an issue with the Ti building process where the .so files are not included during the build and may need manually copying over to the lib folders following the build process.

**Comment by AppWerft** [comment]
Hi Trevor,
I have rebuild against SDK4.1.0.GA and it works. Now I get a license violation at runtime. I have changed the guid and it is fixed. 
Now I can start your streamer and I get:

[ERROR] :  AAS: Error starting stream: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.appwerft.dlrmediathek-2/base.apk"],nativeLibraryDirectories=[/data/app/de.appwerft.dlrmediathek-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libaacdecoder.so"

This is my stream: (Deutschlandfunk)
[INFO] :   http://stream.dradio.de/7/249/142684/v1/gnl.akacast.akamaistream.net/dradio_mp3_dlf_m

I think libaacdecoder.so is missing. How can I solve it?

**Comment by trevorf** [comment]
The module uses the aacdecoder-android lib (version 0.8) available from https://code.google.com/p/aacdecoder-android/downloads/list - you should be able to get the missing .so file from there and this sounds like it relates to the same issue where the build process does not include these during the build.

Alternatively I have a compiled version on the Appc marketplace to download and use immediately if this helps: https://marketplace.appcelerator.com/apps/5762#!overview

**Comment by AppWerft** [comment]
I found this shared objects here:

```
Rainers-MacBook-Pro:ti-android-streamer-master fuerst$ find ./ -name libaacdecoder.so
.//lib/armeabi/libaacdecoder.so
.//lib/armeabi-v7a/libaacdecoder.so
.//lib/mips/libaacdecoder.so
.//lib/x86/libaacdecoder.so
```

I have paid and downloaded. 

```
PLAYING
[DEBUG] :  AACPlayer: play(): decoded 59904 samples
```

What is about:
- streamer.release();
- streamer.isPlaying();

**Comment by trevorf** [comment]
- streamer.release(); - this will release/remove the instance of streamer (every time you require the module a new instance is created)
  streamer.isPlaying(); - this will return a boolean to state if the instance of the streamer is currently playing

**Comment by AppWerft** [comment]
Is this the right pattern :?

``` javascript
function switchUrl(url) {
    if (Streamer.isPlaying() === true) {
        Streamer.stop();
        Streamer.release();     
   }
  Streamer.play(url);
}
```

Or is it too much code?

UPDATE:
[ERROR] :  TiExceptionHandler: (main) [0,19201] - Message: Uncaught TypeError: Object #<Androidaudiostreamer> has no method 'isPlaying'
[ERROR] :  TiExceptionHandler: (main) [0,19201] - Source:               if (Shoutcast.isPlaying()) {
[ERROR] :  V8Exception: Exception occurred at ui/main.menu.js:70: Uncaught TypeError: Object #<Androidaudiostreamer> has no method 'isPlaying'
[I

**Comment by trevorf** [comment]
In this case I don't think you'll need release. The following should work just fine:

```
function switchUrl(url) {
    if (Streamer.isPlaying() === true) {
        Streamer.stop();
   }
  Streamer.play(url);
}
```

**Comment by AppWerft** [comment]
I found isPlaying and release are not implemented. This my code:

``` javascript
var Shoutcast = require('com.woohoo.androidaudiostreamer');
Shoutcast.STOPPED = 0;
Shoutcast.BUFFERING = 1;
Shoutcast.PLAYING = 2;
Shoutcast.STREAMERROR = 3;
Shoutcast.status = 0;
Shoutcast.addEventListener('change', function(_e) {
    Shoutcast.status = _e.status;
    switch (_e.status) {
       case Shoutcast.BUFFERING:
       case Shoutcast.PLAYING:
       case Shoutcast.STOPPED:
    };
});
var switchStation = function(url){
if (Shoutcast.status == Shoutcast.PLAYING) Shoutcast.stop();
Shoutcast.play(url);
}
```

**Comment by m1ga** [comment]
about the error:

```
[ERROR] : AAS: Error starting stream: java.lang.UnsatisfiedLinkError: 
```

you have to place the aacdecoder-android-0.8.jar inside the libs (not lib) folder and the .so files into the libs/ subfolders. Than it builds and runs fine

**Comment by jpriebe** [comment]
BTW -- I think that Shoutcast.stop() may be asynchronous.  I have found that I get better stability when changing streams if I call stop(), and then wait for a status change to STOPPED (status 0) before I start playing the next URL.

If I don't wait for this status change event, the code is unstable when changing streams; after changing streams 4 or 5 times, it will not play any more streams.

**Comment by dieg013** [comment]
Hello, I have this error have you a solution to solve my problem thank you in advance.

``` javascript
E/linker: /data/app/com.myapp/lib/arm/libaacdecoder.so: has text relocations
E/AAS: Error starting stream: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.myapp/lib/arm/libaacdecoder.so: has text relocations
```

**Comment by AppWerft** [comment]
@dieg013 Here https://github.com/AppWerft/DLRmediathek is my project with embedded modules. I hope it helps you.

**Comment by AppWerft** [comment]
There is the method getStatus(), but there is not function isPlaying() or release(). Is it correct?

**Comment by dieg013** [comment]
Hi AppWerft, I still have the same bug you use any version of Appcelerator?

Thank

**Comment by AppWerft** [comment]
I'am using 3.5.1.GA. In this version I have no issue and I'm using a self compiled version of module.

**Comment by AppWerft** [comment]
If you want you can call me at +49 40 60812460 or by kontaktschmied@skype.

Rainer

Am 03/01/16 um 19:11 schrieb dieg013:

> Hi AppWerft, I still have the same bug you use any version of 
> Appcelerator?
> 
> Thank
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/trevorf/ti-android-streamer/issues/3#issuecomment-168525265.

## 

_Dipl.-Ing. Rainer Schleevoigt_
Certified TYPO3 Integrator
Certified Titanium App Developer

```
Novalisweg 10
```

22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||

**Comment by dieg013** [comment]
since I made the last update sdk I arrived more to compile with the older 3.5.1 sdk I have to compile with version 5.1.1GA is why the module does not work I think

Do you speak French ? because I do not speak english :(
