### ISSUE TITLE
Output on console

### ISSUE THREAD

**Issue by AppWerft** [trevorf/ti-android-streamer#4]
Hi Trevor,

your module works partly. The problem is to change ICY-URL. In any cases the app crashes if I try to change. I'am using this code:

``` javascript
var startAudioStreamer = function(m3u) {
    AudioStreamer.stop();
    setTimeout(function() {
        require('controls/resolveplaylist')({
            playlist : m3u,
            onload : function(_icyUrl) {
                console.log('Info: AudioStreamerplayer will play with ' + _icyUrl);
                AudioStreamer.play(_icyUrl + '?' + Math.random());
            }
        });
    }, 2000);
};
```

You have only to methods 'stop' and 'play'. Every 'play'  creates a new Multiplayer (aacPlayer = new MultiPlayer(clb);). I think it is the problem.

Better:
1. method createPlayer()
2. method play  (aacPlayer.playAsync(url);)
3. stop()

Alternatively  we need a method 'release()'.

What do you think about?

Cheers!

Rainer

**Comment by m1ga** [comment]
Quick fix: https://github.com/trevorf/ti-android-streamer/pull/5
